=== muman613/ucode_interface/xml/smpTargetConfig.dtd
<!ELEMENT block ( engine+, control ) >
<!ATTLIST block name ( Audio | Demux | Video ) #REQUIRED >

<!ELEMENT control EMPTY >
<!ATTLIST control hostint CDATA #REQUIRED >
<!ATTLIST control reset CDATA #REQUIRED >

<!ELEMENT dm_map EMPTY >
<!ATTLIST dm_map base CDATA #REQUIRED >
<!ATTLIST dm_map size CDATA #REQUIRED >
<!ATTLIST dm_map width CDATA #REQUIRED >

<!ELEMENT dram_map EMPTY >
<!ATTLIST dram_map base CDATA #REQUIRED >
<!ATTLIST dram_map size CDATA #REQUIRED >

<!ELEMENT em86xxTargetConfig ( target+ ) >
<!ATTLIST em86xxTargetConfig version CDATA #REQUIRED >

<!ELEMENT engine ( io_map, pm_map, dm_map, dram_map ) >
<!ATTLIST engine id ( 0 | 1 | 2 | 3 ) #REQUIRED >

<!ELEMENT io_map EMPTY >
<!ATTLIST io_map base CDATA #REQUIRED >

<!ELEMENT pm_map EMPTY >
<!ATTLIST pm_map base CDATA #REQUIRED >
<!ATTLIST pm_map size CDATA #REQUIRED >

<!ELEMENT target ( block+ ) >
<!ATTLIST target id CDATA #REQUIRED >
<!ATTLIST target type NMTOKEN #FIXED "RiscDSPHard" >
<!ATTLIST target name CDATA #IMPLIED >

=== muman613/ucode_interface/xml/tango_platform_config.xml
<?xml version="1.0"?>
<!DOCTYPE em86xxTargetConfig SYSTEM "smpTargetConfig.dtd">
<em86xxTargetConfig version="2.1">
  <target id="8634" type="RiscDSPHard">
    <block name="Audio">
      <engine id="0">
        <io_map base="0xC0000"/>
        <pm_map base="0x180000" size="0x00004000"/>
        <dm_map base="0x190000" size="0x0000f000" width="1"/>
        <dram_map base="0x10000000" size="0x7fffffff"/>
      </engine>
      <engine id="1">
        <io_map base="0xD0000"/>
        <pm_map base="0x1A0000" size="0x00004000"/>
        <dm_map base="0x1B0000" size="0x0000f000" width="1"/>
        <dram_map base="0x10000000" size="0x7fffffff"/>
      </engine>
      <control hostint="0x3E8A=0x101" reset="0xFFFC"/>
    </block>
    <block name="Demux">
      <engine id="0">
        <io_map base="0xA0000"/>
        <pm_map base="0x140000" size="0x00004000"/>
        <dm_map base="0x150000" size="0x0000f000" width="1"/>
        <dram_map base="0x10000000" size="0x7fffffff"/>
      </engine>
      <control hostint="0x2F0A=0x101" reset="0xFFFC"/>
    </block>
    <block name="Video">
      <engine id="0">
        <io_map base="0x80000"/>
        <pm_map base="0x100000" size="0x00004000"/>
        <dm_map base="0x110000" size="0x0000f000" width="2"/>
        <dram_map base="0x10000000" size="0x7fffffff"/>
      </engine>
      <engine id="1">
        <io_map base="0x90000"/>
        <pm_map base="0x120000" size="0x00004000"/>
        <dm_map base="0x130000" size="0x0000f000" width="2"/>
        <dram_map base="0x10000000" size="0x7fffffff"/>
      </engine>
      <control hostint="0x0FFA=0x101" reset="0xFFFC"/>
    </block>
  </target>

  <target id="8644" type="RiscDSPHard">
    <block name="Audio">
      <engine id="0">
        <io_map base="0xC0000"/>
        <pm_map base="0x180000" size="0x00004000"/>
        <dm_map base="0x190000" size="0x0000f000" width="1"/>
        <dram_map base="0x10000000" size="0x7fffffff"/>
      </engine>
      <engine id="1">
        <io_map base="0xD0000"/>
        <pm_map base="0x1A0000" size="0x00004000"/>
        <dm_map base="0x1B0000" size="0x0000f000" width="1"/>
        <dram_map base="0x10000000" size="0x7fffffff"/>
      </engine>
      <engine id="2">
        <io_map base=""/>
        <pm_map base="0x160000" size="0x00004000"/>
        <dm_map base="0x170000" size="0x0000f000" width="1"/>
        <dram_map base="0x10000000" size="0x7fffffff"/>
      </engine>
      <control hostint="0x3E8A=0x101" reset="0xFFFC"/>
    </block>
    <block name="Demux">
      <engine id="0">
        <io_map base="0xA0000"/>
        <pm_map base="0x140000" size="0x00004000"/>
        <dm_map base="0x150000" size="0x0000f000" width="1"/>
        <dram_map base="0x10000000" size="0x7fffffff"/>
      </engine>
      <control hostint="0x2F0A=0x101" reset="0xFFFC"/>
    </block>
    <block name="Video">
      <engine id="0">
        <io_map base="0x80000"/>
        <pm_map base="0x100000" size="0x00004000"/>
        <dm_map base="0x110000" size="0x0000f000" width="2"/>
        <dram_map base="0x10000000" size="0x7fffffff"/>
      </engine>
      <engine id="1">
        <io_map base="0x90000"/>
        <pm_map base="0x120000" size="0x00004000"/>
        <dm_map base="0x130000" size="0x0000f000" width="2"/>
        <dram_map base="0x10000000" size="0x7fffffff"/>
      </engine>
      <control hostint="0x0FFA=0x101" reset="0xFFFC"/>
    </block>
  </target>

  <target id="8646" type="RiscDSPHard">
    <block name="Audio">
      <engine id="0">
        <io_map base="0xC0000"/>
        <pm_map base="0x180000" size="0x00004000"/>
        <dm_map base="0x190000" size="0x0000f000" width="1"/>
        <dram_map base="0x10000000" size="0x7fffffff"/>
      </engine>
      <engine id="1">
        <io_map base="0xD0000"/>
        <pm_map base="0x1A0000" size="0x00004000"/>
        <dm_map base="0x1B0000" size="0x0000f000" width="1"/>
        <dram_map base="0x10000000" size="0x7fffffff"/>
      </engine>
      <engine id="2">
        <io_map base=""/>
        <pm_map base="0x160000" size="0x00004000"/>
        <dm_map base="0x170000" size="0x0000f000" width="1"/>
        <dram_map base="0x10000000" size="0x7fffffff"/>
      </engine>
      <control hostint="0x3E8A=0x101" reset="0xFFFC"/>
    </block>
    <block name="Demux">
      <engine id="0">
        <io_map base="0xA0000"/>
        <pm_map base="0x140000" size="0x00004000"/>
        <dm_map base="0x150000" size="0x0000f000" width="1"/>
        <dram_map base="0x10000000" size="0x7fffffff"/>
      </engine>
      <control hostint="0x2F0A=0x101" reset="0xFFFC"/>
    </block>
    <block name="Video">
      <engine id="0">
        <io_map base="0x80000"/>
        <pm_map base="0x100000" size="0x00004000"/>
        <dm_map base="0x110000" size="0x0000f000" width="2"/>
        <dram_map base="0x10000000" size="0x7fffffff"/>
      </engine>
      <engine id="1">
        <io_map base="0x90000"/>
        <pm_map base="0x120000" size="0x00004000"/>
        <dm_map base="0x130000" size="0x0000f000" width="2"/>
        <dram_map base="0x10000000" size="0x7fffffff"/>
      </engine>
      <control hostint="0x0FFA=0x101" reset="0xFFFC"/>
    </block>
  </target>

  <target id="8652" type="RiscDSPHard">
    <block name="Audio">
      <engine id="0">
        <io_map base="0xC0000"/>
        <pm_map base="0x180000" size="0x00004000"/>
        <dm_map base="0x190000" size="0x0000f000" width="1"/>
        <dram_map base="0x10000000" size="0x7fffffff"/>
      </engine>
      <engine id="1">
        <io_map base="0xD0000"/>
        <pm_map base="0x1A0000" size="0x00004000"/>
        <dm_map base="0x1B0000" size="0x0000f000" width="1"/>
        <dram_map base="0x10000000" size="0x7fffffff"/>
      </engine>
      <control hostint="0x3E8A=0x101" reset="0xFFFC"/>
    </block>
    <block name="Demux">
      <engine id="0">
        <io_map base="0xA0000"/>
        <pm_map base="0x140000" size="0x00004000"/>
        <dm_map base="0x150000" size="0x0000f000" width="1"/>
        <dram_map base="0x10000000" size="0x7fffffff"/>
      </engine>
      <control hostint="0x2F0A=0x101" reset="0xFFFC"/>
    </block>
    <block name="Video">
      <engine id="0">
        <io_map base="0x80000"/>
        <pm_map base="0x100000" size="0x00004000"/>
        <dm_map base="0x110000" size="0x0000f000" width="2"/>
        <dram_map base="0x10000000" size="0x7fffffff"/>
      </engine>
      <engine id="1">
        <io_map base="0x90000"/>
        <pm_map base="0x120000" size="0x00004000"/>
        <dm_map base="0x130000" size="0x0000f000" width="2"/>
        <dram_map base="0x10000000" size="0x7fffffff"/>
      </engine>
      <control hostint="0x0FFA=0x101" reset="0xFFFC"/>
    </block>
  </target>

  <target id="8654" type="RiscDSPHard">
    <block name="Audio">
      <engine id="0">
        <io_map base="0xC0000"/>
        <pm_map base="0x180000" size="0x00004000"/>
        <dm_map base="0x190000" size="0x0000f000" width="1"/>
        <dram_map base="0x10000000" size="0x7fffffff"/>
      </engine>
      <engine id="1">
        <io_map base="0xD0000"/>
        <pm_map base="0x1A0000" size="0x00004000"/>
        <dm_map base="0x1B0000" size="0x0000f000" width="1"/>
        <dram_map base="0x10000000" size="0x7fffffff"/>
      </engine>
      <control hostint="0x3E8A=0x101" reset="0xFFFC"/>
    </block>
    <block name="Demux">
      <engine id="0">
        <io_map base="0xA0000"/>
        <pm_map base="0x140000" size="0x00004000"/>
        <dm_map base="0x150000" size="0x0000f000" width="1"/>
        <dram_map base="0x10000000" size="0x7fffffff"/>
      </engine>
      <control hostint="0x2F0A=0x101" reset="0xFFFC"/>
    </block>
    <block name="Video">
      <engine id="0">
        <io_map base="0x80000"/>
        <pm_map base="0x100000" size="0x00004000"/>
        <dm_map base="0x110000" size="0x0000f000" width="2"/>
        <dram_map base="0x10000000" size="0x7fffffff"/>
      </engine>
      <engine id="1">
        <io_map base="0x90000"/>
        <pm_map base="0x120000" size="0x00004000"/>
        <dm_map base="0x130000" size="0x0000f000" width="2"/>
        <dram_map base="0x10000000" size="0x7fffffff"/>
      </engine>
      <control hostint="0x0FFA=0x101" reset="0xFFFC"/>
    </block>
  </target>

  <target id="8656" type="RiscDSPHard">
    <block name="Audio">
      <engine id="0">
        <io_map base="0xC0000"/>
        <pm_map base="0x180000" size="0x00004000"/>
        <dm_map base="0x190000" size="0x0000f000" width="1"/>
        <dram_map base="0x10000000" size="0x7fffffff"/>
      </engine>
      <engine id="1">
        <io_map base="0xD0000"/>
        <pm_map base="0x1A0000" size="0x00004000"/>
        <dm_map base="0x1B0000" size="0x0000f000" width="1"/>
        <dram_map base="0x10000000" size="0x7fffffff"/>
      </engine>
      <control hostint="0x3E8A=0x101" reset="0xFFFC"/>
    </block>
    <block name="Demux">
      <engine id="0">
        <io_map base="0xA0000"/>
        <pm_map base="0x140000" size="0x00004000"/>
        <dm_map base="0x150000" size="0x0000f000" width="1"/>
        <dram_map base="0x10000000" size="0x7fffffff"/>
      </engine>
      <control hostint="0x2F0A=0x101" reset="0xFFFC"/>
    </block>
    <block name="Video">
      <engine id="0">
        <io_map base="0x80000"/>
        <pm_map base="0x100000" size="0x00004000"/>
        <dm_map base="0x110000" size="0x0000f000" width="2"/>
        <dram_map base="0x10000000" size="0x7fffffff"/>
      </engine>
      <engine id="1">
        <io_map base="0x90000"/>
        <pm_map base="0x120000" size="0x00004000"/>
        <dm_map base="0x130000" size="0x0000f000" width="2"/>
        <dram_map base="0x10000000" size="0x7fffffff"/>
      </engine>
      <control hostint="0x0FFA=0x101" reset="0xFFFC"/>
    </block>
  </target>

  <target id="8670" type="RiscDSPHard">
    <block name="Audio">
      <engine id="0">
        <io_map base="0xC0000"/>
        <pm_map base="0x180000" size="0x00004000"/>
